### PR TITLE
Update .rubocop.yml

### PR DESCRIPTION
**Pull request by lukaselmer**
@coorasse what do you think?

### CODE REVIEW

**Comment by coorasse** [comment]
I like this check. It prepares our apps for the new ruby version and I see no good reason in removing it.
It adds a line in all the files, right, this may be annoying, but it does with zero-pain for us.

**Comment by lukaselmer** [comment]
> It adds a line in all the files, right, this may be annoying, but it does with zero-pain for us.
To me it feels painful to add an additional line of code to EVERY ruby file per project. Especially when Ruby 3 is far far away...? tbd with the team.

**Comment by lukaselmer** [comment]
I'll revert the merge of the #5 until we've discussed this issue

**Comment by diegosteiner** [comment]
TBD in a break (since it's easier than writing everything down).

**Pull request merged**
